- hosts: web
  become: true
  gather_facts: false
  
  tasks:
    - name: Install NGINX web service 
      apt: 
        name=nginx
        state=absent
        
    - name: Create target web folders
      file: 
        path: /var/www/html
        state: directory
        mode: 0755

    - name: Deploy custom web pages
      copy:
       src: ~/Downloads/eatveg/eatveg-html/
       dest: /var/www/html/
     




     
